version: 2

sources:
  - name: 'production'
    description: 'The source is from the Adventure Works repository'
    schema: sap_adw
    tables:
      - name: 'product'
        description: 'This tables brings general information of the products of the establishment'
        columns:
          - name: 'productid'
            description: 'This column brings the Id fo the products and is also de Primary Key of this table'
            tests:
            - unique
            - not_null

          - name: 'subcategorysubcategoryCode'
            description: 'This column brings the code of the product subcategory Id,
              is a Foreing Key of the table Product_Subcategory'
            tests:
            - unique
            - not_null

          - name: 'productmodelCode'
            description: 'This column brings the code of the product model Id, is a Foreing Key of the table Model' 
            tests:
              - unique
              - not_null

          - name: 'name'
            description: 'This column brings the name of the product'

          - name: 'productnumber'
            description: 'This column brings the internal code of the product'

          - name: 'makeflag'
            description: This column brings the manufacturing type of the product'

          - name: 'finishedgoodsflag'
            description: 'This column brings the status of the product, it indicates when its ready for sale'

          - name: 'color'
            description: 'This column brings the color of the product'

          - name: 'safetystocklevel'
            description: 'This column brings the minimal level status in stock of the product'

          - name: 'reorderpoint'
            description: 'This column indicates the stocks level  point number to reorder product for stock'

          - name: 'standardcost'
            description: 'This column brings the product cost price'

          - name: 'listprice'
            description: 'This column brings the product sells price'

          - name: 'size'
            description: 'This column brings the dimensions of the product'

          - name: 'daystomanufacture'
            description: 'This column brings the needed totalo days to manufecture the product'

          - name: 'productline'
            description: 'This column brings the status of the final use of the product, for example, for road, for mountain'

          - name: 'class'
            description: 'This column brings the classification of the product in order to its quality as High, Medium and Low'

          - name: 'style'
            description: 'This column brings the gender of the product'

          - name: 'sellstartdate'
            description: 'This column brings the date of the start sells oh the product'

          - name: 'sellenddate'
            description: 'This column brings the date when the product became Unavailable'

      - name: 'productcategory'
        description: 'This table brings information of the category type of the products'
        columns:
          - name: 'productcategoryid'
            description: 'This column is the Primery Key of this table'
            tests:
              - unique
              - not_null

          - name: 'name'
            description: 'This columns brings the description of the category. Ex: Components, Clothing, Acessories'

      - name: 'productsubcategory'
        description: 'This table brings information of the subcategory type of the products'
        columns:
          - name: 'productsubcategoryid'
            description: 'This column is the Primery Key of this table'
            tests:
              - unique
              - not_null

          - name: 'productcategoryCode'
            description: 'This column brings de Product Category Id, is the Forein Key of the table stg_erp_Product_Category '
            tests:
              - unique
              - not_null

          - name: 'name'
            description: 'This columns brings the description of the subcategory. Ex: Chain, Gloves, Socks'

