version: 2

sources:
  - name: 'humanresources'
    schema: sap_adw
    description: 'The source is from the Adventure Works repository'
    tables:
      - name: 'department'
        description: 'This table bring the general information from Adventure Works departments'
        columns:
          - name: 'departmentid'
            description: 'This column brings the Pk of this table'
            tests:
              - unique
              - not_null

          - name: 'name'
            description: 'This column brings the Department name description'

          - name: 'groupname'
            description: 'This column brings the Department Group name description'

      - name: 'employee'
        description: 'This table brings general information from the employees, as departament, vacation hours, sickleave days and job title'
        columns:
          - name: 'loginid'
            description: 'This column ir the Pk from this table, e is going to be the Sk for Dim_Employee'
            tests:
              - unique
              - not_null

          - name: 'businessentityid'
            description: 'This Column is one of the Pk from this table, is going to be used for join with table Department'
            tests:
              - unique
              - not_null

          - name: 'jobtitle'
            description: 'This column brings the description of the employee role, as Engineering Manager, Design Engineer, Sales Representative'

          - name: 'gender'
            description: 'This column brings the employee gender'

          - name: 'hiredate'
            description: 'This column brings the employee hired date'

          - name: 'salariedflag'
            description: 'Hiring regime: No = Hourly, not exempt from collective bargaining. Yes = Salaried person, exempt from collective bargaining'

          - name: 'vacationhours'
            description: 'This columns brings the employee available vacation hours'

          - name: 'currentflag'
            description: 'This column brings the hired situation of the employee: No = Inactive, Yes = Aticve'

          - name: 'sickleavehours'
            description: 'This columns brings the number of the employee sick leave hours'

      - name: 'employeedepartmenthistory'
        description: 'This table brings the departament history from de employee'
        columns:
          - name: 'businessentityid'
            description: 'This is the Pk from this table as column BusinessPersonId 
              It is going to be important for the join with the department table, this way, is going to be possible identifier the Employee Id with his department'
            tests:
              - unique
              - not_null

          - name: 'departmentid'
            description: 'This column is one of the Pk from this table, e is going to be used for the join with department table.'
